#pragma once
#include <Arduino.h>
#include "SpriteAssets.h"

// Generated by firmware/tools/user_emotes/build_user_emotes.py.
// Run that tool after adding PNG layers in firmware/user_emotes.

struct UserEmoteAsset {
  const char* name;
  uint16_t weight;
  unsigned long durationMs;
  const SparseAsset* asset;
};

constexpr uint8_t USER_EMOTE_COUNT = 0;
constexpr uint16_t USER_EMOTE_TOTAL_WEIGHT = 0;

static const UserEmoteAsset USER_EMOTES[] = {
  {"", 0, 0, nullptr}
};
